### ISSUE TITLE
ecbuild_find_omp can't find find_package_handle_standard_args if LAPACK_PATH is set for OOPS

### ISSUE THREAD

**Issue by DJDavies2** [JCSDA/ecbuild#13]
I had a weird ecbuild failure when attempting to compile OOPS on its own.  I wanted to compile OOPS against a custom built LAPACK (3.8.0, built via cmake), so I did

`ecbuild .... -DLAPACK_PATH=/path/to/lapack/install ...`  

I am using cmake 3.13.4.  It failed like this:

CMake Error at /home/h01/frwd/cylc-run/mi-ay727/share/gnu_6_rhel7/ecbuild/share/ecbuild/cmake/ecbuild_find_omp.cmake:173 (find_package_handle_standard_args):
  Unknown CMake command "find_package_handle_standard_args".
Call Stack (most recent call first):
  /home/h01/frwd/cylc-run/mi-ay727/share/gnu_6_rhel7/ecbuild/share/ecbuild/cmake/ecbuild_add_option.cmake:252 (ecbuild_find_omp)
  CMakeLists.txt:63 (ecbuild_add_option)

It wasn't immediately clear to me why adding a bespoke LAPACK build would cause OpenMP detection to fail.  By comparing the ecbuild output when run with --trace I think that what is happening is that when there is no LAPACK_PATH option the code path goes through FindLAPACK and FindBLAS; in FindBLAS there is the line include(FindPackageHandleStandardArgs).  When LAPACK_PATH is set the code path instead goes through the cmake files in the LAPACK installation directory (lapack-config.cmake and friends) which doesn't include this line.

Adding the missing include to line 173 of cmake/ecbuild_find_omp.cmake seems to work, i.e.

```
    include(FindPackageHandleStandardArgs)
    find_package_handle_standard_args( OMP${_STUBS}_${_LANG} REQUIRED_VARS ${_LANG}_COMPILER_SUPPORTS_OMP${_STUBS}  )
```
This is similar to how the Check*SourceCompiles functions are handled on line 148; the include is done just before the functions are called.  I would push a branch with this fix but I don't seem to have permission.

**Comment by mmiesch** [comment]
Thanks @DJDavies2 for this fix.  It does seem to me to be something that they would like to include in the upstream ecmwf version.
I just gave you write access to the jcsda fork of ecbuild but unfortunately
[The develop branch of our jcsda fork is in transition at the moment](https://github.com/JCSDA/ecbuild/issues/12).
So, I think the best way to proceed would be for you to create a branch of jcsda::ecbuild that is identical to the upstream fork apart from this change.  Then we can do a pull request to ecmwf - either you can do it or I can do it on your behalf.  If you do it I think you'll have to e-sign a contributor agreement first.  Then, we can merge that branch both into our develop and their develop.  I don't think this overlaps any other active work so there should not be any merge conflicts.

**Comment by markjolah** [comment]
Note that via github you can now check in a branch to the JCSDA fork and generate a PR against the upstream ecmwf.  You just change the leftmost dropdown to select to merge against ecmwf/develop.  To do this cleanly I found the best way was to add the ecmwf upstream repo as an alternate remote, and then use git cherry-pick to add in just your one commit to a branch that begins at ecmwf/develop.

**Comment by DJDavies2** [comment]
I've tried to create a branch and pull request (see https://github.com/ecmwf/ecbuild/pull/14) but it seems to have gone horribly wrong, it is trying to merge a bunch of other commits that are unrelated to mine; it also seems to be trying to merge with ECMWF's ecbuild instead of JCSDA's.  Sorry about this.

**Comment by DJDavies2** [comment]
I've changed the base of the merge to ecmwf:develop and the reduces the extraneous stuff but there is still quite a log there.

**Comment by markjolah** [comment]
Sorry if I wasn't clear before, as I was trying to warn you about just this scenario, since I just did the same thing.  In your local repo:
```
git remote add ecmwf https://github.com/ecmwf/ecbuild
git switch -c feature/my_upstream_patch ecmwf/develop
git cherry-pick <commit-sha1>
git push origin feature/my_upstream_patch
```
Then when on github go to JCSDA/ecbuild and click on the yellow PR banner and set the leftmost box to merge against ecmwf/develop.

**Comment by DJDavies2** [comment]
Hmm, I think my version of git is too old for that:

frwd@vld544:> git switch -c feature/my_upstream_patch ecmwf/develop
git: 'switch' is not a git command. See 'git --help'.
/home/h01/frwd/roses/mi-ay727/ecbuild_jcsda
frwd@vld544:> git --version
git version 2.16.5

Maybe I should just redo the change directly on a branch of ECMWF's ecbuild?

**Comment by mmiesch** [comment]
Yes - I meant to comment on that - switch is a very new command, introduced just in version 2.23.  An alternative would be something like this:
~~~~~
git remote add ecmwf https://github.com/ecmwf/ecbuild
git fetch ecmwf
git checkout -b feature/my_upstream_patch ecmwf/develop
git cherry-pick <commit-sha1>
git push origin feature/my_upstream_patch
~~~~~
If you don't want to use the cherry-pick command you can just make your change again and commit it.

**Comment by DJDavies2** [comment]
I've had another got creating a new branch.  Is this any better?

https://github.com/JCSDA/ecbuild/pull/14

**Comment by DJDavies2** [comment]
It appears that the fix for this is not part of the 3.1.0.jcsda2 tag; is it possible to create a tag with this fix in please?

**Comment by mmiesch** [comment]
Ah yes - sorry @DJDavies2 - this got merged into release/stable but not develop, which is our working branch again.  Just lost in the shuffle during the transition.  I've got to run to another meeting now but I'll issue another patch later today.  Are you working with a particular container that you would like updated or are you working from your own installation of ecbuild?

**Comment by DJDavies2** [comment]
I'm working with my own installation of ecbuild.

**Comment by mmiesch** [comment]
Ok - So for now I won't bother rebuilding the containers.  But, the patch is there so I'll go ahead and close this issue - let us know if you continue to have problems.
