### ISSUE TITLE
RPATH handling and "intel old linker bug"

### ISSUE THREAD

**Issue by markjolah** [JCSDA/ecbuild#36]
I looked into what is happening with the linker flags situation for ecbuild, in particular why ecbuild is adding extra linker flags.  The patch applied in #16 is not really what the problem is.

The real problem is that ECMWF has set some default options which are not necessary for the JEDI project and are leading to some of these issues.  In particular everything in `ecbuild_check_os.cmake` is totally unnecessary for us, and the ECMWF specific requirements are being imposed on everyone by default.   We don't use RPATH or RUNPATH for JEDI projects so the `-Wl,--disable-new-dtags` is totally unnecessary, and the `--allow-shlib-undefined` is both unnecessary and wrong.

The way to fix these issues is to set the following options
`ECBUILD_DISABLE_NEW_DTAGS=OFF` and `ECBUILD_DISABLE_RPATH_FIX=ON`.  Ecbuild is going to set these variables to the opposite settings by default, so each JEDI package (or bundle) needs to set the following code:
```
#JEDI packages do not use RPATH - Disable ECMWF hard coded options which manipulate linker flags unnecessarily
set( ECBUILD_DISABLE_NEW_DTAGS OFF CACHE STRING "Disabled ecbuild feature (OFF=disabled)" FORCE)
set( ECBUILD_DISABLE_RPATH_FIX ON CACHE STRING "Disabled ecbuild feature (ON=disabled)" FORCE)
```

With these settings the "old linker fix" is unnecessary because the entire feature is turned off.  The best place to put this code would be in a "toolchain" file, but we don't have those yet.  My proposal is to keep the "old linker fix" locally for now, it doesn't make sense to push it upstream anyways.  We need to eventually start building with toolchains and we can add the above code there to fix the problem.  Once this is fixed with toolchains everywhere relevant, remove the "old linker fix" and everything should be OK.

**Comment by markjolah** [comment]
PS. I was looking for a github label like "discussion" but "question" is about as close as I found.

**Comment by mmiesch** [comment]
Thanks @markjolah - yes, I agree it doesn't make much sense to push it upstream.  And, to answer your question @rickgrubin - 
>What's the easiest way to test the potential fix? Looks like you tested "bugfix/intel-shlib-undefined" bugfix branch, your comments say "I tested this on the two main problem platforms, namely S4 and the (ubuntu 16) intel 17 container and all seems well."  so I'll test as you did. Thanks.

The answer is that it's almost irrelevant now.   We're now using intel 19 for CI so I have no plans to continue to maintain intel 17.  And, I think they updated their software on S4 so it's no longer an issue (though it's worth checking).   If it is still a problem on S4, you can just [add these flags to the toolchain](https://github.com/JCSDA/jedi-toolchains/blob/develop/jcsda-S4-Intel.cmake), which I do use, by the way (I'm not sure if anyone else does).

So, I think the current ecbuild tag is the last one that we should support this with.   In the future we can just use upstream and set the flags if needed, as @markjolah suggests.
