### ISSUE TITLE
Coordination of JCSDA/ecbuild release/stable PR merges into develop branch

### ISSUE THREAD

**Issue by markjolah** [JCSDA/ecbuild#5]
Creating this topic primarily to organize the merging of accepted PRs from the release/stable to the develop branch.

Not sure what the best method to manage this is but it will be advisable to keep the common merges coordinated with the two branches.  

I used a git cherry-pick operation for [PR #1](https://github.com/JCSDA/ecbuild/pull/1), which was submitted against develop and subsequently merged to release/stable

We need to add the following to develop
 *  [~PR #3~](https://github.com/JCSDA/ecbuild/pull/3)
 *  [~PR #4~](https://github.com/JCSDA/ecbuild/pull/4)

I can manage this.  Just wanted to make sure we were coordinated, and see if there are any other git tricks to manage this situation any better.

**Comment by aerorahul** [comment]
@markjolah #6 repeats #4, but with a PR on top of develop.

**Comment by markjolah** [comment]
Ok.  I suppose this is one way to do it.  Maybe it's easier to not make a separate PR, as we have essentially already approved the changes once.  I suppose for complex change sets we may need separate PRs for each version of ecbuild as there may be complex interactions to consider, but for simple things it may just create noise.  At the minimum we don't really need to re-review the PR merge into develop.

**Comment by aerorahul** [comment]
@markjolah. I agree on not needing to re-review simple stuff.  
Referencing a PR (to a previous PR) can be useful in tracking down.
Also, if we do squash and merge, it will be a single commit, so minimal noise in the log.

**Comment by markjolah** [comment]
OK.  This sounds good.  [PR#3](https://github.com/JCSDA/ecbuild/issues/3) was already fixed in develop.  Therefore develop is now up-to-date.  I suppose if we just make a policy that whomever does the actual merge into release/stable also does the corresponding develop PR and merge, then we can just close this issue.
